-- Crear la base de datos
CREATE DATABASE DB_PROYECTOPIII;
USE DB_PROYECTOPIII;

-- Tabla de Roles
CREATE TABLE GP_ROL (
    ROL_ID INT AUTO_INCREMENT PRIMARY KEY,
    ROL_NOMBRE VARCHAR(50) UNIQUE NOT NULL,
    ROL_STATUS VARCHAR(20) NOT NULL -- Para eliminación lógica
);

-- Tabla de Usuarios
CREATE TABLE GP_USUARIO (
    USU_ID INT AUTO_INCREMENT PRIMARY KEY,
    USU_NOMBRE VARCHAR(100) NOT NULL,
    USU_EMAIL VARCHAR(100) UNIQUE NOT NULL,
    USU_PASSWORD VARCHAR(255) NOT NULL,
    USU_STATUS VARCHAR(20) NOT NULL, -- Para eliminación lógica
    ROL_ID INT,
    FOREIGN KEY (ROL_ID) REFERENCES GP_ROL(ROL_ID)
);

-- Tabla de Compradores (hereda de GP_USUARIO)
CREATE TABLE GP_COMPRADOR (
    COM_ID INT AUTO_INCREMENT PRIMARY KEY,
    USU_ID INT NOT NULL UNIQUE,
    COM_STATUS VARCHAR(20) NOT NULL, -- Para eliminación lógica
    FOREIGN KEY (USU_ID) REFERENCES GP_USUARIO(USU_ID) ON DELETE CASCADE
);

-- Tabla de Vendedores (hereda de GP_USUARIO)
CREATE TABLE GP_VENDEDOR (
    VEN_ID INT AUTO_INCREMENT PRIMARY KEY,
    USU_ID INT NOT NULL UNIQUE,
    VEN_STATUS VARCHAR(20) NOT NULL, -- Para eliminación lógica
    FOREIGN KEY (USU_ID) REFERENCES GP_USUARIO(USU_ID) ON DELETE CASCADE
);

-- Tabla de Vehículos
CREATE TABLE GP_VEHICULO (
    VEH_ID INT AUTO_INCREMENT PRIMARY KEY,
    VEN_ID INT NOT NULL,
    VEH_MARCA VARCHAR(50) NOT NULL,
    VEH_MODELO VARCHAR(50) NOT NULL,
    VEH_ANO INT NOT NULL,
    VEH_PRECIO_BASE DECIMAL(10,2) NOT NULL,
    VEH_ESTADO VARCHAR(20) NOT NULL, -- Estado del vehículo (Disponible, Subastado, Vendido)
    VEH_STATUS VARCHAR(20) NOT NULL, -- Para eliminación lógica
    FOREIGN KEY (VEN_ID) REFERENCES GP_VENDEDOR(VEN_ID) ON DELETE CASCADE
);

-- Tabla de Subastas
CREATE TABLE GP_SUBASTA (
    SUB_ID INT AUTO_INCREMENT PRIMARY KEY,
    SUB_FECHA_INICIO DATETIME NOT NULL,
    SUB_FECHA_FIN DATETIME NOT NULL,
    SUB_ESTADO VARCHAR(20) NOT NULL, -- Estado de la subasta (Activa, Finalizada, Cancelada)
    SUB_STATUS VARCHAR(20) NOT NULL, -- Para eliminación lógica
    VEN_ID INT NOT NULL,
    FOREIGN KEY (VEN_ID) REFERENCES GP_VENDEDOR(VEN_ID) ON DELETE CASCADE
);

-- Tabla Intermedia Subasta-Vehículos
CREATE TABLE GP_SUBASTA_VEHICULO (
    SUB_ID INT NOT NULL,
    VEH_ID INT NOT NULL,
    SUB_VEH_STATUS VARCHAR(20) NOT NULL, -- Para eliminación lógica
    PRIMARY KEY (SUB_ID, VEH_ID),
    FOREIGN KEY (SUB_ID) REFERENCES GP_SUBASTA(SUB_ID) ON DELETE CASCADE,
    FOREIGN KEY (VEH_ID) REFERENCES GP_VEHICULO(VEH_ID) ON DELETE CASCADE
);

-- Tabla de Pujas
CREATE TABLE GP_PUJAS (
    PUJ_ID INT AUTO_INCREMENT PRIMARY KEY,
    SUB_ID INT NOT NULL,
    COM_ID INT NOT NULL,
    PUJ_MONTO DECIMAL(10,2) NOT NULL,
    PUJ_STATUS VARCHAR(20) NOT NULL, -- Para eliminación lógica
    FOREIGN KEY (SUB_ID) REFERENCES GP_SUBASTA(SUB_ID) ON DELETE CASCADE,
    FOREIGN KEY (COM_ID) REFERENCES GP_COMPRADOR(COM_ID) ON DELETE CASCADE
);
